name: V1 Builds

on: [push, pull_request]

#on:
#  schedule:
#    # On 45-th minute, every 6 hours
#    - cron:  '45 */6 * * *'
#
#  push:
#    branches:
#    - 'v1-**'
#    paths-ignore:
#    - data/**
#    - docs/**
#    - '**/*.md'
#  pull_request:
#    branches:
#    - 'v1-**'
#    paths-ignore:
#    - data/**
#    - docs/**
#    - '**/*.md'

jobs:
  build:

    name: ${{ matrix.machine }}-{{ matrix.branch }}
    runs-on: ubuntu-latest
    needs: generate

    strategy:
      fail-fast: false # Allow all machines to finish building
      matrix:
        branch:
        - 2.0.5.3
        machine:
        - MP3DP/MRambo_16T_aero
        #- MP3DP/Ramps_16T_MK
        ##- MPCNC/Archim1_T8_16T_LCD
        ##- MPCNC/Archim1_T8_16T_LCD_DualEndstop
        ##- MPCNC/Archim2_T8_16T_LCD_16step
        #- MPCNC/MRambo_T8_16T_LCD
        #- MPCNC/Rambo_T8_16T_LCD
        #- MPCNC/Rambo_T8_16T_LCD_DualEndstop
        #- MPCNC/Ramps_T8_16T_LCD_32step
        #- MPCNC/Ramps_T8_16T_LCD_32step_DualEndstop
        #- MPCNC/SKR1.3_T8_16T_LCD_32step
        #- MPCNC/SKR1.3_T8_16T_LCD_32step_DualEndstop
        #- MPCNC/SKRPro1.1_T8_16T_LCD_32step_DualEndstop
        #- ZenXY/MiniRambo_16T
        #- ZenXY/Ramps_16T_LCD_32
        #- Lowrider/SKR1.3_T8_16T_LCD_32step_DualDrivers

    steps:
    - uses: actions/checkout@v2
    - run: .github/scripts/configure-git
    - name: Check out MarlinFirmware
      run: |
        git clone http://github.com/MarlinFirmware/Marlin.git --depth 1 --branch "${{ matrix.branch }}"

    # Based on .github/workflows/test-builds.yml
    - name: Select Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/master.zip
        platformio update

    - name: Build
      run: |
        v1-scripts/build-for-machine ${{ matrix.machine }}
        v1-scripts/build-zips ${{ matrix.machine }}

        #- name: Release
        #  uses: ncipollo/release-action@v1
        #  with:
        #    artifacts: ".zip/*.zip,.bin/*"
        #    #bodyFile: "body.md"
        #    token: ${{ secrets.GITHUB_TOKEN }}
        #    prerelease: true
        #    name: unstable
        #    # FIXME: This needs to be dynamic and possibly use a different action
        #    # e.g. https://github.com/actions/create-release/pull/12
        #    tag: v1-bugfix-2.0.x-auto
        #    commit: ${{ github.ref }}
        #    allowUpdates: true
